import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'
import { addTaskComment, addTaskLabel, assignTask, createTask, getContext, getMemoryById, getSddArtifact, getSddArtifactByKey, getSddChange, getSddSpec, getSddSpecByCapability, getTask, getUsageSummary, linkSddChangeMemory, linkTaskSpec, listClients, listConventions, listMemories, listMyTasks, listProjects, listSddChanges, listSddSpecs, listTasks, locateCode, promoteMemory, recordDecision, reportUsage, resolveTasksForSpec, saveSddArtifact, saveSddSpec, searchMemories, searchSddArtifacts, storeConvention, storeMemory, updateMemory, updateSddChange, updateTask } from './client.js'
import { descriptorSchema, EffectClass, FABRIC_VERSION, REGISTRY_VERSION, ToolDefinition, ToolFabric } from './tool-fabric.js'

const string = (description: string) => z.string().describe(description)
const optionalString = (description: string) => z.string().optional().describe(description)
const integer = (description: string) => z.number().int().min(1).max(200).optional().describe(description)
const count = (description: string) => z.number().int().min(0).optional().describe(description)
const stringArray = (description: string) => z.array(z.string()).optional().describe(description)
const MEMORY_TYPES = ['architecture', 'bugfix', 'decision', 'discovery', 'config', 'pattern', 'feedback', 'preference', 'project', 'session_summary', 'feature', 'refactoring', 'manual'] as const
const memoryType = () => z.enum(MEMORY_TYPES).optional().describe('Memory type')
const TASK_STATUSES = ['backlog', 'todo', 'in_progress', 'in_review', 'done', 'cancelled'] as const
const taskStatus = () => z.enum(TASK_STATUSES).optional().describe('Task status')
const TASK_PRIORITIES = ['low', 'medium', 'high', 'urgent'] as const
const taskPriority = () => z.enum(TASK_PRIORITIES).optional().describe('Task priority')

const definitions: ToolDefinition[] = [
  tool('search_memories', 'Search team memories without returning schemas by default.', ['memory.search'], ['memory:read'], { query: string('Semantic query'), limit: integer('Maximum results') }, z.object({ query: z.string(), limit: z.number().int().min(1).max(200).optional() }), args => searchMemories(args as { query: string; limit?: number })),
  tool('list_memories', 'Browse team memories with bounded filters.', ['memory.list'], ['memory:read'], { project: optionalString('Project'), limit: integer('Maximum results') }, z.object({ project: z.string().optional(), limit: z.number().int().min(1).max(200).optional() }), args => listMemories(args)),
  tool('get_memory', 'Fetch one authorized memory by id.', ['memory.read'], ['memory:read'], { id: string('Memory id') }, z.object({ id: z.string() }), args => getMemoryById(args.id as string)),
  tool('list_projects', 'List projects visible to the caller.', ['project.list'], ['project:read'], { include_archived: z.boolean().optional() }, z.object({ include_archived: z.boolean().optional() }), args => listProjects(args)),
  tool('list_sdd_changes', 'List SDD change metadata, never document content.', ['sdd.list'], ['sdd:read'], { project: optionalString('Project'), include_archived: z.boolean().optional() }, z.object({ project: z.string().optional(), include_archived: z.boolean().optional() }), args => listSddChanges(args)),
  tool('list_sdd_specs', 'List living specification metadata.', ['sdd.specs.list'], ['sdd:read'], { project: optionalString('Project'), include_archived: z.boolean().optional() }, z.object({ project: z.string().optional(), include_archived: z.boolean().optional() }), args => listSddSpecs(args)),
  tool('search_sdd_artifacts', 'Search SDD snippets without returning full documents.', ['sdd.search'], ['sdd:read'], { query: string('Search query'), limit: integer('Maximum hits') }, z.object({ query: z.string(), limit: z.number().int().min(1).max(200).optional() }), args => searchSddArtifacts(args.query as string, args.limit as number | undefined)),
  tool('locate_code', 'Rank distinct file paths for a query — read these before scanning files, saving tokens.', ['code.locate'], ['memory:search'], { project: string('Indexed project key'), query: string('What to find'), limit: integer('Maximum files') }, z.object({ project: z.string(), query: z.string(), limit: z.number().int().min(1).max(200).optional() }), args => locateCode(args as { project: string; query: string; limit?: number })),
  tool('list_clients', 'List clients visible to the caller — the top of the client hierarchy.', ['client.list'], ['client:read'], { include_archived: z.boolean().optional() }, z.object({ include_archived: z.boolean().optional() }), args => listClients(args)),
  tool('get_usage_summary', 'Aggregated usage rollup (tokens + duration) at a chosen level. Admin-scoped server-side.', ['usage.summary'], ['memory:read'], { level: optionalString('task|project|client|org|model|user'), from: optionalString('Range start'), to: optionalString('Range end'), client_id: optionalString('Filter client'), project_id: optionalString('Filter project') }, z.object({ level: z.string().optional(), from: z.string().optional(), to: z.string().optional(), client_id: z.string().optional(), project_id: z.string().optional() }), args => getUsageSummary(args as { level?: 'task' | 'project' | 'client' | 'org' | 'model' | 'user'; from?: string; to?: string; client_id?: string; project_id?: string })),
  tool('get_context', 'Session bootstrap: team conventions (highest authority) plus recent memories for a project.', ['context.read'], ['memory:read'], { project: optionalString('Project'), limit: integer('Max memories') }, z.object({ project: z.string().optional(), limit: z.number().int().min(1).max(200).optional() }), args => getContext(args as { project?: string; limit?: number })),
  tool('list_conventions', 'List active team conventions — the rules agents follow first.', ['convention.list'], ['convention:read'], { category: optionalString('Filter category'), project: optionalString('Project'), include_archived: z.boolean().optional() }, z.object({ category: z.string().optional(), project: z.string().optional(), include_archived: z.boolean().optional() }), args => listConventions(args.category as string | undefined, args.include_archived as boolean | undefined, args.project as string | undefined)),
  tool('list_tasks', 'List team tasks with bounded filters.', ['task.list'], ['task:read'], { project: optionalString('Project'), status: taskStatus(), assignee: optionalString('Assignee id or "me"'), limit: integer('Maximum results') }, z.object({ project: z.string().optional(), status: z.enum(TASK_STATUSES).optional(), assignee: z.string().optional(), limit: z.number().int().min(1).max(200).optional() }), args => listTasks(args)),
  tool('list_my_tasks', 'List tasks assigned to the calling agent (server resolves "me").', ['task.list.mine'], ['task:read'], { project: optionalString('Project'), status: taskStatus(), limit: integer('Maximum results') }, z.object({ project: z.string().optional(), status: z.enum(TASK_STATUSES).optional(), limit: z.number().int().min(1).max(200).optional() }), args => listMyTasks(args)),
  tool('store_memory', 'Persist a decision, bug fix, convention, or discovery. Requires content; add title + type + project.', ['memory.store'], ['memory:write'], { content: string('Full memory content'), title: optionalString('Short searchable title'), type: memoryType(), topic_key: optionalString('Stable upsert key'), scope: z.enum(['project', 'personal']).optional().describe('project (default) or personal'), project: optionalString('Project'), tags: stringArray('Tags') }, z.object({ content: z.string(), title: z.string().optional(), type: z.enum(MEMORY_TYPES).optional(), topic_key: z.string().optional(), scope: z.enum(['project', 'personal']).optional(), project: z.string().optional(), tags: z.array(z.string()).optional() }), args => storeMemory(args as unknown as Parameters<typeof storeMemory>[0]), ['write']),
  tool('update_memory', 'Correct one memory by id — content and/or tags.', ['memory.update'], ['memory:write'], { id: string('Memory id'), content: optionalString('New content'), tags: stringArray('Replacement tags') }, z.object({ id: z.string(), content: z.string().optional(), tags: z.array(z.string()).optional() }), args => updateMemory(args as { id: string; content?: string; tags?: string[] }), ['write']),
  tool('record_decision', 'Record a structured ADR (context, options, decision, rationale, consequences).', ['decision.record'], ['memory:write'], { title: string('Decision title'), context: string('Why the decision was needed'), options_considered: z.array(z.string()).min(1).describe('Options evaluated'), decision: string('What was chosen'), rationale: string('Why it won'), consequences: optionalString('Follow-up/risks'), project: optionalString('Project'), tags: stringArray('Extra tags') }, z.object({ title: z.string(), context: z.string(), options_considered: z.array(z.string()).min(1), decision: z.string(), rationale: z.string(), consequences: z.string().optional(), project: z.string().optional(), tags: z.array(z.string()).optional() }), args => recordDecision(args as unknown as Parameters<typeof recordDecision>[0]), ['write']),
  tool('store_convention', 'Establish a team convention (rule) with optional category and weight.', ['convention.store'], ['convention:write'], { content: string('Convention text'), title: optionalString('Short title'), category: optionalString('Category'), weight: count('Priority weight') }, z.object({ content: z.string(), title: z.string().optional(), category: z.string().optional(), weight: z.number().int().min(0).optional() }), args => storeConvention(args as { content: string; title?: string; category?: string; weight?: number }), ['write']),
  tool('create_task', 'Create a team task under a project.', ['task.create'], ['task:write'], { project: string('Project'), title: string('Task title'), description: optionalString('Details'), status: taskStatus(), priority: taskPriority(), due_date: optionalString('Due date (ISO)') }, z.object({ project: z.string(), title: z.string(), description: z.string().optional(), status: z.enum(TASK_STATUSES).optional(), priority: z.enum(TASK_PRIORITIES).optional(), due_date: z.string().optional() }), args => createTask(args as unknown as Parameters<typeof createTask>[0]), ['write']),
  tool('update_task', 'Advance or edit a task by id (status, priority, title, description).', ['task.update'], ['task:write'], { task_id: string('Task id'), status: taskStatus(), priority: taskPriority(), title: optionalString('New title'), description: optionalString('New description'), due_date: optionalString('Due date (ISO)') }, z.object({ task_id: z.string(), status: z.enum(TASK_STATUSES).optional(), priority: z.enum(TASK_PRIORITIES).optional(), title: z.string().optional(), description: z.string().optional(), due_date: z.string().optional() }), args => { const { task_id, ...rest } = args as { task_id: string } & Record<string, unknown>; return updateTask(task_id, rest) }, ['write']),
  tool('report_usage', 'Report one work event (tokens + duration) for a project/task/session.', ['usage.report'], ['memory:write'], { project: optionalString('Project'), task_id: optionalString('Task id'), session_id: optionalString('Session id'), model: optionalString('Model name'), tokens_in: count('Input tokens'), tokens_out: count('Output tokens'), duration_ms: count('Duration ms') }, z.object({ project: z.string().optional(), task_id: z.string().optional(), session_id: z.string().optional(), model: z.string().optional(), tokens_in: z.number().int().min(0).optional(), tokens_out: z.number().int().min(0).optional(), duration_ms: z.number().int().min(0).optional() }), args => reportUsage(args as unknown as Parameters<typeof reportUsage>[0]), ['write']),
  tool('promote_memory', 'Promote a client/project-scoped memory into an org-wide asset (explicit, lineage kept).', ['memory.promote'], ['memory:write'], { id: string('Memory id to promote') }, z.object({ id: z.string() }), args => promoteMemory(args.id as string), ['write']),

  // ── Tasks (detail + mutations the tasks skill invokes) ──────────────────────
  tool('get_task', 'Fetch one task by id, with its full detail.', ['task.read'], ['task:read'], { task_id: string('Task id') }, z.object({ task_id: z.string() }), args => getTask(args.task_id as string)),
  tool('assign_task', 'Assign a task to one or more users (replaces the current assignees).', ['task.assign'], ['task:write'], { task_id: string('Task id'), user_ids: z.array(z.string()).min(1).describe('User ids') }, z.object({ task_id: z.string(), user_ids: z.array(z.string()).min(1) }), args => assignTask(args.task_id as string, args.user_ids as string[]), ['write']),
  tool('add_task_comment', 'Add a comment to a task.', ['task.comment'], ['task:write'], { task_id: string('Task id'), body: string('Comment body') }, z.object({ task_id: z.string(), body: z.string() }), args => addTaskComment(args.task_id as string, args.body as string), ['write']),
  tool('add_task_label', 'Add a label to a task.', ['task.label'], ['task:write'], { task_id: string('Task id'), label: string('Label') }, z.object({ task_id: z.string(), label: z.string() }), args => addTaskLabel(args.task_id as string, args.label as string), ['write']),
  tool('link_task_spec', 'Link a task to an SDD change by its name.', ['task.link_spec'], ['task:write'], { task_id: string('Task id'), spec_change_name: string('SDD change name') }, z.object({ task_id: z.string(), spec_change_name: z.string() }), args => linkTaskSpec(args.task_id as string, args.spec_change_name as string), ['write']),
  tool('resolve_tasks_for_spec', 'List the tasks linked to an SDD change.', ['task.resolve_spec'], ['task:read'], { spec_change_name: string('SDD change name') }, z.object({ spec_change_name: z.string() }), args => resolveTasksForSpec(args.spec_change_name as string)),

  // ── SDD artifacts and specs (the read/write the sdd-* skills call each phase) ─
  tool('save_sdd_artifact', 'Persist an SDD artifact (proposal, spec delta, design, tasks, reports). Idempotent by content hash; creates the change if absent.', ['sdd.artifact.save'], ['sdd:write'], { project: string('Project'), change_name: string('Change name'), kind: string('Artifact kind (proposal, spec, design, tasks, …)'), content: string('Full document content'), capability: optionalString('Capability (required for kind=spec)'), path: optionalString('Repo-relative file path'), git_commit: optionalString('Commit sha'), git_ref: optionalString('Git ref') }, z.object({ project: z.string(), change_name: z.string(), kind: z.string(), content: z.string(), capability: z.string().optional(), path: z.string().optional(), git_commit: z.string().optional(), git_ref: z.string().optional() }), args => saveSddArtifact(args as unknown as Parameters<typeof saveSddArtifact>[0]), ['write']),
  tool('get_sdd_artifact', 'Fetch one SDD artifact by id — the FULL document, never a preview.', ['sdd.artifact.read'], ['sdd:read'], { artifact_id: string('Artifact id') }, z.object({ artifact_id: z.string() }), args => getSddArtifact(args.artifact_id as string)),
  tool('get_sdd_artifact_by_key', 'Fetch the latest SDD artifact by its natural key (project, change, kind, capability?).', ['sdd.artifact.read'], ['sdd:read'], { project: string('Project'), change_name: string('Change name'), kind: string('Artifact kind'), capability: optionalString('Capability (for kind=spec)') }, z.object({ project: z.string(), change_name: z.string(), kind: z.string(), capability: z.string().optional() }), args => getSddArtifactByKey(args as unknown as Parameters<typeof getSddArtifactByKey>[0])),
  tool('get_sdd_change', 'Fetch an SDD change with its artifact inventory — the recoverable state of a change.', ['sdd.change.read'], ['sdd:read'], { change_id: string('Change id') }, z.object({ change_id: z.string() }), args => getSddChange(args.change_id as string)),
  tool('update_sdd_change', 'Transition an SDD change (phase/status/title/sprint).', ['sdd.change.update'], ['sdd:write'], { change_id: string('Change id'), phase: optionalString('New phase'), status: optionalString('New status'), title: optionalString('New title'), sprint_id: optionalString('Sprint id') }, z.object({ change_id: z.string(), phase: z.string().optional(), status: z.string().optional(), title: z.string().optional(), sprint_id: z.string().optional() }), args => { const { change_id, ...rest } = args as { change_id: string } & Record<string, unknown>; return updateSddChange(change_id, rest) }, ['write']),
  tool('link_sdd_change_memory', 'Link a decision/bugfix memory to the SDD change that produced or informed it.', ['sdd.change.link_memory'], ['sdd:write'], { change_id: string('Change id'), memory_id: string('Memory id'), relation: z.enum(['produced', 'informed']).optional().describe('produced (default) or informed') }, z.object({ change_id: z.string(), memory_id: z.string(), relation: z.enum(['produced', 'informed']).optional() }), args => { const { change_id, ...rest } = args as { change_id: string } & Record<string, unknown>; return linkSddChangeMemory(change_id, rest as unknown as Parameters<typeof linkSddChangeMemory>[1]) }, ['write']),
  tool('save_sdd_spec', 'Persist a living capability spec (the source-of-truth that archive merges deltas into).', ['sdd.spec.save'], ['sdd:write'], { project: string('Project'), capability: string('Capability'), content: string('Full spec content'), title: optionalString('Title'), path: optionalString('Repo-relative path'), merged_from_change_name: optionalString('Change whose deltas this merges'), git_commit: optionalString('Commit sha') }, z.object({ project: z.string(), capability: z.string(), content: z.string(), title: z.string().optional(), path: z.string().optional(), merged_from_change_name: z.string().optional(), git_commit: z.string().optional() }), args => saveSddSpec(args as unknown as Parameters<typeof saveSddSpec>[0]), ['write']),
  tool('get_sdd_spec', 'Fetch one living capability spec by id — the full document.', ['sdd.spec.read'], ['sdd:read'], { spec_id: string('Spec id') }, z.object({ spec_id: z.string() }), args => getSddSpec(args.spec_id as string)),
  tool('get_sdd_spec_by_capability', 'Fetch the living spec for a capability by (project, capability).', ['sdd.spec.read'], ['sdd:read'], { project: string('Project'), capability: string('Capability') }, z.object({ project: z.string(), capability: z.string() }), args => getSddSpecByCapability(args.project as string, args.capability as string)),
]

function tool(name: string, summary: string, capabilities: string[], permissions: string[], shape: Record<string, unknown>, input: z.ZodType<Record<string, unknown>>, run: (args: Record<string, unknown>) => Promise<unknown>, effects: EffectClass[] = ['read']): ToolDefinition {
  const handle = `tool://nexusmind/${name}@${FABRIC_VERSION}`
  const properties = Object.fromEntries(Object.entries(shape).map(([key, value]) => [key, zodJsonSchema(value)]))
  const required = Object.entries(shape).filter(([, value]) => !isOptional(value)).map(([key]) => key)
  return { name, namespace: 'nexusmind', summary, capabilities, io: { input: 'object', output: 'json' }, effects, permissions, cost: 'low', latency: 'medium', failures: ['backend_error', 'permission_denied', 'invalid_args'], schema_handle: handle, version: FABRIC_VERSION, schema: { type: 'object', properties, ...(required.length > 0 ? { required } : {}), additionalProperties: false }, examples: [{ args: {}, description: 'Use only fields documented by load_tool.' }], input, run }
}

function isOptional(value: unknown): boolean {
  return (value as { _def?: { typeName?: string } })?._def?.typeName === 'ZodOptional'
}

function zodJsonSchema(value: unknown): Record<string, unknown> {
  const definition = (value as { _def?: { typeName?: string; innerType?: unknown; valueType?: unknown } })._def
  if (!definition) return { type: 'object' }
  if (definition.typeName === 'ZodOptional') return zodJsonSchema(definition.innerType)
  if (definition.typeName === 'ZodString') return { type: 'string' }
  if (definition.typeName === 'ZodNumber') return { type: 'number' }
  if (definition.typeName === 'ZodBoolean') return { type: 'boolean' }
  if (definition.typeName === 'ZodEnum') return { type: 'string' }
  if (definition.typeName === 'ZodArray') return { type: 'array' }
  if (definition.typeName === 'ZodRecord') return { type: 'object' }
  return { type: 'object' }
}

export async function startReducedReadonly(): Promise<void> {
  const server = new McpServer({ name: 'nexusmind-reduced-readonly', version: REGISTRY_VERSION })
  const fabric = new ToolFabric(definitions)

  server.tool('find_tools', 'Discover compact authorized tool descriptors. Schemas are not included.', { query: z.string().optional(), effect_class: z.enum(['read', 'write', 'delete']).optional(), permissions: z.array(z.string()).default([]) }, async ({ query, effect_class, permissions }) => ({ content: [{ type: 'text', text: JSON.stringify({ profile: 'reduced_readonly', registry_version: REGISTRY_VERSION, tools: fabric.findTools(query, effect_class, permissions) }) }] }))
  server.tool('load_tool', 'Load the schema for one authorized tool handle.', { handle: z.string(), permissions: z.array(z.string()).default([]) }, async ({ handle, permissions }) => { const loaded = fabric.loadTool(handle, permissions); return { content: [{ type: 'text', text: JSON.stringify({ schema: descriptorSchema(loaded), examples: loaded.examples, version: loaded.version, registry_version: REGISTRY_VERSION, expires_in_ms: 300000 }) }] } })
  server.tool('execute_tool', 'Execute one loaded, versioned, authorized tool (reads and non-destructive writes; deletes are refused).', { handle: z.string(), version: z.string(), args: z.record(z.unknown()), permissions: z.array(z.string()).default([]) }, async ({ handle, version, args, permissions }) => { try { const result_handle = await fabric.executeTool(handle, args, version, permissions); return { content: [{ type: 'text', text: JSON.stringify({ result_handle, version, expires_in_ms: 300000 }) }] } } catch (error) { return { content: [{ type: 'text', text: (error as Error).message }], isError: true } } })
  server.tool('fetch', 'Fetch only a bounded page of a result handle.', { handle: z.string(), cursor: z.string().optional(), range: z.object({ start: z.number().int().min(0).optional(), end: z.number().int().min(0).optional() }).optional(), permissions: z.array(z.string()).default([]) }, async ({ handle, cursor, range, permissions }) => { try { return { content: [{ type: 'text', text: JSON.stringify(fabric.fetchResult(handle, range, cursor, permissions)) }] } } catch (error) { return { content: [{ type: 'text', text: (error as Error).message }], isError: true } } })

  await server.connect(new StdioServerTransport())
}

export { definitions }
